CD: Add support for building and publishing x86_64 Windows executables

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -90,16 +90,16 @@ jobs:
               run: flutter pub get
 
             # --- SIGNING SETUP ---
-            - name: Decode Keystore
-              run: |
-                  echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
+            # - name: Decode Keystore
+            #   run: |
+            #       echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
 
-            - name: Create key.properties
-              run: |
-                  echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" > android/key.properties
-                  echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
-                  echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
-                  echo "storeFile=upload-keystore.jks" >> android/key.properties
+            # - name: Create key.properties
+            #   run: |
+            #       echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" > android/key.properties
+            #       echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
+            #       echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
+            #       echo "storeFile=upload-keystore.jks" >> android/key.properties
 
             # --- BUILD APKs ---
             - name: Build Split APKs
@@ -110,47 +110,47 @@ jobs:
                 flutter build apk --release --split-per-abi \
                   --dart-define=APP_VERSION="$APP_VERSION" \
                   --dart-define=APP_BUILD="$APP_BUILD"
-            - name: Zipalign and Resign APKs
-              run: |
-                  # 1. Dynamically find the latest version of apksigner
-                  # We look inside build-tools, sort in reverse to get the highest version, and pick the top one.
-                  APKSIGNER=$(find $ANDROID_HOME/build-tools -name "apksigner" | sort -r | head -n 1)
+            # - name: Zipalign and Resign APKs
+            #   run: |
+            #       # 1. Dynamically find the latest version of apksigner
+            #       # We look inside build-tools, sort in reverse to get the highest version, and pick the top one.
+            #       APKSIGNER=$(find $ANDROID_HOME/build-tools -name "apksigner" | sort -r | head -n 1)
 
-                  if [ -z "$APKSIGNER" ]; then
-                    echo "Error: apksigner not found in $ANDROID_HOME/build-tools"
-                    exit 1
-                  fi
+            #       if [ -z "$APKSIGNER" ]; then
+            #         echo "Error: apksigner not found in $ANDROID_HOME/build-tools"
+            #         exit 1
+            #       fi
 
-                  echo "Using apksigner: $APKSIGNER"
+            #       echo "Using apksigner: $APKSIGNER"
 
-                  cd build/app/outputs/apk/release
+            #       cd build/app/outputs/apk/release
 
-                  for apk in *.apk; do
-                    # --- Step A: Zipalign ---
-                    mv "$apk" "${apk%.apk}-unaligned.apk"
+            #       for apk in *.apk; do
+            #         # --- Step A: Zipalign ---
+            #         mv "$apk" "${apk%.apk}-unaligned.apk"
 
-                    python3 ${{ github.workspace }}/reproducible-apk-tools/zipalign.py \
-                      --page-size 16 \
-                      --pad-like-apksigner \
-                      --replace \
-                      "${apk%.apk}-unaligned.apk" \
-                      "$apk"
+            #         python3 ${{ github.workspace }}/reproducible-apk-tools/zipalign.py \
+            #           --page-size 16 \
+            #           --pad-like-apksigner \
+            #           --replace \
+            #           "${apk%.apk}-unaligned.apk" \
+            #           "$apk"
 
-                    rm "${apk%.apk}-unaligned.apk"
+            #         rm "${apk%.apk}-unaligned.apk"
 
-                    # --- Step B: Resign the APK ---
-                    # Make sure your keystore path and secret names match your repo setup
+            #         # --- Step B: Resign the APK ---
+            #         # Make sure your keystore path and secret names match your repo setup
 
-                    "$APKSIGNER" sign \
-                      --ks ${{ github.workspace }}/android/app/upload-keystore.jks \
-                      --ks-pass pass:${{ secrets.ANDROID_STORE_PASSWORD }} \
-                      --key-pass pass:${{ secrets.ANDROID_KEY_PASSWORD }} \
-                      --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
-                      "$apk"
+            #         "$APKSIGNER" sign \
+            #           --ks ${{ github.workspace }}/android/app/upload-keystore.jks \
+            #           --ks-pass pass:${{ secrets.ANDROID_STORE_PASSWORD }} \
+            #           --key-pass pass:${{ secrets.ANDROID_KEY_PASSWORD }} \
+            #           --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
+            #           "$apk"
 
-                     # Verify it
-                     "$APKSIGNER" verify --verbose "$apk"
-                  done
+            #          # Verify it
+            #          "$APKSIGNER" verify --verbose "$apk"
+            #       done
 
             - name: Upload Android Artifacts
               uses: actions/upload-artifact@v7
@@ -231,10 +231,74 @@ jobs:
                   path: |
                     *linux-x86_64.tar.gz
                     *linux-x86_64.AppImage
-                    
+
+    build_windows_x86_64:
+        name: Build Release windows
+        needs: [get-version-info]
+        runs-on: windows-2022
+        env:
+          WORKING_DIR: build/windows/x64/runner/Release/
+
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
+
+            - name: Setup Flutter
+              uses: subosito/flutter-action@v2
+              with:
+                  channel: "stable"
+                  flutter-version-file: pubspec.yaml
+                  cache: true
+            
+            - name: Install dependencies
+              run: flutter pub get
+
+            - name: Get version from pubspec.yaml
+              shell: pwsh
+              run: |
+                $versionLine = Select-String -Path pubspec.yaml -Pattern '^version:\s*([0-9]+\.[0-9]+\.[0-9]+)'
+                if ($versionLine -match '([0-9]+\.[0-9]+\.[0-9]+)') {
+                    $VERSION = $Matches[1]
+                    echo "VERSION=$VERSION" >> $env:GITHUB_ENV
+                } else {
+                    Write-Error "Version not found in pubspec.yaml"
+                }  
+
+            - name: Build Windows App
+              env:
+                APP_VERSION: ${{ needs.get-version-info.outputs.version }}
+                APP_BUILD: ${{ needs.get-version-info.outputs.build_number }}
+              run: |
+                flutter build windows --release `
+                  --dart-define=APP_VERSION="${{ env.APP_VERSION }}" `
+                  --dart-define=APP_BUILD="${{ env.APP_BUILD }}"
+            
+            # See https://docs.flutter.dev/platform-integration/windows/building#building-your-own-zip-file-for-windows      
+            - name: Add runtime files
+              run: |
+                Copy-Item "C:\Windows\System32\msvcp140.dll" "${{env.WORKING_DIR}}"
+                Copy-Item "C:\Windows\System32\vcruntime140.dll" "${{env.WORKING_DIR}}"
+                Copy-Item "C:\Windows\System32\vcruntime140_1.dll" "${{env.WORKING_DIR}}"
+            
+            - name: Add app icon
+              run: Copy-Item assets/icon-cricle.png ${{env.WORKING_DIR}}/my_quran.png
+
+            - name: Create portable version
+              run: Compress-Archive -Path "${{env.WORKING_DIR}}*" -DestinationPath "MyQuran-$env:VERSION-windows-x86_64.zip"
+            
+            - name: Compile .ISS to .EXE Installer
+              run: iscc /DMyAppVersion=$env:VERSION windows/packaging/inno-setup.iss
+              
+            - name: Upload Windows Artifacts
+              uses: actions/upload-artifact@v7
+              with:
+                  name: windowsBuilds_x64_86
+                  path: |
+                    *windows-x86_64.zip
+                    *windows-x86_64-setup.exe  
     release:
         name: Publish Release
-        needs: [build_android, build_linux_x86_64, get-version-info]
+        needs: [build_android, build_linux_x86_64, build_windows_x86_64, get-version-info]
         runs-on: ubuntu-latest
 
         steps:
@@ -251,6 +315,11 @@ jobs:
                   name: linuxBuilds_x64_86
                   path: artifacts
 
+            - uses: actions/download-artifact@v7
+              with:
+                  name: windowsBuilds_x64_86
+                  path: artifacts      
+
             - name: Create GitHub Release
               uses: ncipollo/release-action@v1
               with:
@@ -261,7 +330,9 @@ jobs:
                   artifacts: >
                     artifacts/*.apk,
                     artifacts/*.tar.gz,
-                    artifacts/*.AppImage
+                    artifacts/*.AppImage,
+                    artifacts/*.zip,
+                    artifacts/*.exe
                   token: ${{ secrets.GITHUB_TOKEN }}
                  
     build_web_artifact:
